### ISSUE TITLE
Can't change hardcoded port 8080

### ISSUE THREAD

**Issue by k0ste** [openkilt/openrepo#9]
Hi, I was modify docker-compose to expose port 80

```yaml
version: "3.9"
services:
  nginx:
    image: openkilt/openrepo:latest
    command: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - "django"
    volumes:
      - ./openrepo-data:/var/lib/openrepo
```

But when I'm try to curl repo without trailing slash, OpenRepo return url with port number

```bash
√ ~ % curl -v http://openrepo.opentech.local/infra-el8  <--- request without port number
*   Trying 100.100.101.22:80...
* Connected to openrepo.opentech.local (100.100.101.22) port 80 (#0)
> GET /infra-el8 HTTP/1.1
> Host: openrepo.opentech.local
> User-Agent: curl/7.87.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 301 Moved Permanently
< Server: nginx/1.18.0 (Ubuntu)
< Date: Thu, 11 May 2023 13:06:34 GMT
< Content-Type: text/html
< Content-Length: 178
< Location: http://openrepo.opentech.local:8080/infra-el8/  <-------- problem here
< Connection: keep-alive
<
<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.18.0 (Ubuntu)</center>
</body>
</html>
* Connection #0 to host openrepo.opentech.local left intact
```

I was try to resolve this via definition env `OPENREPO_DOMAIN` to host:80 - seems this option isn't working for this case as well

**Comment by matthill** [comment]
You'll want to forward to port 8080 inside Docker, rather than port 80.

The Nginx config inside the Docker container exposes two ports: 80 and 8080.  Port 80 is just there to forward to SSL/443 (i.e., you want to serve exclusively HTTPS content, and as a convenience, auto redirect people who hit the HTTP endpoint).  

In your case, I believe you just want to forward the HTTP app (8080).  So the following config I think should be what you want.

```
version: "3.9"
services:
  nginx:
    image: openkilt/openrepo:latest
    command: nginx
    restart: unless-stopped
    ports:
      - "80:8080"
    depends_on:
      - "django"
    volumes:
      - ./openrepo-data:/var/lib/openrepo
```
